# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  name: 'CP-Azure-agent-VM'

variables: 
  - name: dockerImageName

steps: 
- task: Maven@3
  displayName: 'Maven Package'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/jre-openjdk'
    mavenVersionOption: 'Path'
    mavenDirectory: '/opt/maven'
    mavenSetM2Home: true
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CopyFiles@2
  displayName: 'Copy Files to artifact'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.?(war|jar)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'imagebuild7 / react'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 
      tag1
      tag2
- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'imagebuild7 / react'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      beta.1
      latest

- task: Bash@3
  displayName: "Removing docker image"
  inputs:
    targetType: 'inline'
    script: 'docker rmi -f $(docker images -q $(dockerImageName))'